#!/bin/bash

YELLOW="\033[1;33m"
RESET="\033[1;m"

# shellcheck disable=SC2046
if [ ! $(which groovyclient) ]; then
  GROOVYSERV_INSTALL="${YELLOW}sdk install groovyserv${RESET}"
  echo -e "Install groovyclient/groovyserv with: $GROOVYSERV_INSTALL"
  exit 1
fi

# Executing doesn't do much for what I want: grab an non zero exit code
# So I'm using a wrapper to colorize the output for now
exec groovyclient \
-cp vendor/spock-core-1.3-groovy-2.5.jar:src/main/groovy/:src/main/java/ \
./src/test/groovy/snappy/dev/env/AppTest.groovy
