#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rainbow'

out = Rainbow(`./manage/dev/test-run`)

if out.include?('Test Failure:') # I couldn't find a way to grab a non zero exit code from the test runner
  print(out.red)
  print(Time.now)
  system('tmux set -q status-left-bg red') if ENV['TMUX']
  return
end

puts(out.green.bold)
print(Time.now)
system('tmux set -q status-left-bg green') if ENV['TMUX']
