#!/bin/bash

set -e

YELLOW="\033[1;33m"
BLUE="\033[1;34m"
RESET="\033[1;m"

# PATH is not available after the pipe
JAVAC=$(which javac)

function timestamp() {
  /bin/date --rfc-333=seconds
}

# NOTE: command line options inconsistencies
#  - java 8: -version
#  - java 11: --version
JAVA_VERSION=$($JAVAC -version 2>&1)
echo -e "Using java compiler: ${BLUE}${JAVA_VERSION}${RESET}"

# shellcheck disable=SC2046
if [ ! $(which inotifywait) ]; then
  APT_GET_INSTALL="${YELLOW}apt-get install inotify-tools${RESET}"
  echo -e "Install inotifywait with: $APT_GET_INSTALL"
  exit 1
fi


echo "[$(timestamp)] Killing previous groovyserv daemon"
groovyserver -k

echo "[$(timestamp)] Generating *.class files on first run"

JAVA_SRC="./src/main/java"

# Most performant version
# find $JAVA_SRC -name "*.java" -print0 | xargs -0 javac

# Let's see if the better visibility is worth it
find $JAVA_SRC -name "*.java" -print0 | xargs -0 -n1 --verbose javac

echo "[$(timestamp)] Now starting the watch process"
# shellcheck disable=SC2162
inotifywait --recursive --quiet --monitor --event close_write $JAVA_SRC  |
  while read DIR _ FILENAME; do
    if [[ $FILENAME != *.java ]]; then
      continue
    fi

    PATH="${DIR}${FILENAME}"
    echo "[$(timestamp)] javac $PATH"

    $JAVAC "$PATH"
  done
